version: "3.7"

services:
  db:
    image: mysql:8.0.22
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3310:3306"
    expose:
      - "3310"
    volumes:
      - stocks-db:/var/lib/mysql
  app:
    build: .
    env_file:
      - .env
    environment:
      PORT: 8888
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: "db"
      DB_PORT: 3306
      ENV: ${ENV}
    ports:
      - "8889:8888"
    depends_on:
      - db
    command: sh -c './wait-for db:3306 -- npm run-script dev'
    expose:
      - "8889"

volumes:
  stocks-db:
